#!/bin/bash

# safety
set -e

# debugging
# set -x

git config --get remote.origin.url | {
  read origin
  # git@github.com:e3krisztian/bead.git
  origin=${origin#*github.com?}
  origin=${origin%.git}
  USER=${origin%/*}
  PROJECT=${origin#*/}
  # get branch
  BRANCH=$(git symbolic-ref --short -q HEAD)

  # static correctness
  flake8 --max-line-length=100 --show-source $PROJECT

  # update TODO section of README.md
  TEMPREADME=$(mktemp --tmpdir=. README-TODOS-XXX)
  {
    sed '0,/^## TODO/p;d' README.md
    printf '\nUpdated by script, text in this section and afterwards will be overwritten\n\n'
    git grep -n -e FIXME -e TODO -e XXX -- '*.py' |
      sed 's=^\([^:]*\):\([0-9]*\):\s*\(.*\)=- [\3](https://github.com/'$USER/$PROJECT/blob/$BRANCH'/\1#L\2)='
  } > "$TEMPREADME"
  mv "$TEMPREADME" README.md
}

# check in interactively
git gui
