#!/bin/bash

# safety
set -e

# debugging
# set -x

# update TODO section of README.md
TEMPREADME=$(mktemp --tmpdir=. README-TODOS-XXX)
git remote get-url origin | {
  read origin
  # git@github.com:e3krisztian/lib.git
  origin=${origin#*github.com?}
  origin=${origin%.git}
  USER=${origin%/*}
  PROJECT=${origin#*/}
  # get branch
  BRANCH=$(git status -b --porcelain | head -1 | sed 's/^## \([-a-zA-Z0-9_]*\).*/\1/')
  sed '0,/^## TODO/p;d' README.md
  printf '\nUpdated by script, text will be overwritten after this section\n\n'
  git grep -n -e FIXME -e TODO -e XXX -- '*.py' |
    sed 's=^\([^:]*\):\([0-9]*\):\s*\(.*\)=- [\3](https://github.com/'$USER/$PROJECT/blob/$BRANCH'/\1#L\2)='
} > "$TEMPREADME"
mv "$TEMPREADME" README.md

# check in interactively
git gui
