#!/bin/sh
cd $(dirname "$0")

[ -d test-env ] || make test-env || exit 1
. test-env/bin/activate

pwd
flake8 bead bead_cli
set -x
if [ $# = 0 ]; then
  exec green bead bead_cli
else
  exec green "$@"
fi
