name: Nox CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.12]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Nox
        run: pip install nox
      - name: Run Nox session for correct Python version
        run: |
          if [[ "${{ matrix.python-version }}" == "3.8" ]]; then
            nox -s tests_3_8
          elif [[ "${{ matrix.python-version }}" == "3.12" ]]; then
            nox -s tests_3_12
          fi
