name: Build and Upload Executables

on:
  release:
    types: [published]
    tags:
      - 'v*'

jobs:
  build-executables:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code at tag
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build executables
        run: make executables
      - name: Upload executables to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            executables/bead
            executables/bead.cmd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
